services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
